/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Latitude E7250
 */
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class ForActualizar extends javax.swing.JFrame {
    
    
    private UserCRUD crud;
    /**
     * Creates new form ForActualizar
     */
    public ForActualizar() {
        initComponents();
        crud = new UserCRUD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btnbuscarporid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtid = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtnombre = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtcorreo = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtcontrasena = new javax.swing.JTextPane();
        btn_act_nombre = new javax.swing.JButton();
        btn_act_correo = new javax.swing.JButton();
        btn_act_contrasena = new javax.swing.JButton();

        jScrollPane4.setViewportView(jTextPane3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Actualizar Usuario");

        btnbuscarporid.setText("Buscar por ID");
        btnbuscarporid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarporidActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtid);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Correo", "Contraseña"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Correo:");

        jLabel4.setText("Contraseña:");

        jScrollPane3.setViewportView(txtnombre);

        jScrollPane5.setViewportView(txtcorreo);

        jScrollPane6.setViewportView(txtcontrasena);

        btn_act_nombre.setText("Actualizar");
        btn_act_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_act_nombreActionPerformed(evt);
            }
        });

        btn_act_correo.setText("Actualizar");
        btn_act_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_act_correoActionPerformed(evt);
            }
        });

        btn_act_contrasena.setText("Actualizar");
        btn_act_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_act_contrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbuscarporid)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_act_correo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_act_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(btn_act_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbuscarporid)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btn_act_nombre)))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_act_correo))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_act_contrasena))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarporidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarporidActionPerformed
   //1. Obtener el valor del txt
       String idtext = txtid.getText();
       
       //2. Validar txt vacio
       if(idtext.isEmpty()){
           JOptionPane.showMessageDialog(this, "El id es obligatorio", "Error",JOptionPane.ERROR_MESSAGE);
           return;
       }
       //3.Busqueda y llenado de la tabla
       try{
           int id = Integer.parseInt(idtext);
           ResultSet rs = crud.buscarPorID(id);
           DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
           modelo.setRowCount(0);
           
           if(rs.next()){
               modelo.addRow(new Object[]{rs.getInt("id"),rs.getString("nombre"),rs.getString("correo"),rs.getString("contrasena")});
           }
       }
       catch(SQLException e){
           System.out.println("Error al llenar la tabla: "+e.getMessage());
           
       }
    }//GEN-LAST:event_btnbuscarporidActionPerformed

    private void btn_act_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_act_nombreActionPerformed
        // TODO add your handling code here:
        //1. Se guarda en la variable lo que el usuario a ingresado
        
        String nom=btn_act_nombre.getText();
        String id=btnbuscarporid.getText();
        
        //2. Se valida que no existan vacíos
        
        if(nom.isEmpty()){
            
            JOptionPane.showMessageDialog(this, "El campo es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //3. El usuario ingresa dato para actualizar el campo de nombre
        
        UserCRUD crud = new UserCRUD();
     
        
        //4. Se pregunta al usuario si desea actualizar el campo
        int respuesta = JOptionPane.showConfirmDialog(
            null, 
            "¿Estás seguro de que quieres actualizar el nombre?", 
            "Confirmar actualización", 
            JOptionPane.YES_NO_OPTION
        );
        
        if (respuesta == JOptionPane.YES_OPTION){
            
                //5. Se muestra el status de la actualización/UPDATE
                
            //Si selecciona la opción "YES/SI" se hace la actualización 
            
            boolean status=crud.actualizar_nombre_usuario(nom, id);
            if(status){
                
            
       JOptionPane.showMessageDialog(this,"Nombre del usuario actualizado", "Éxito",JOptionPane.INFORMATION_MESSAGE);
            
        }
            
        }
            
        else
        {       
            //En caso contrario muestra el siguiente mensaje:
            JOptionPane.showMessageDialog(this,"Nombre del usuario no actualizado", "No actualizado",JOptionPane.INFORMATION_MESSAGE);  
        }
       limpiarcampos();
    }//GEN-LAST:event_btn_act_nombreActionPerformed

    private void btn_act_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_act_correoActionPerformed
        // TODO add your handling code here:
        //1. Se guarda en la variable lo que el usuario a ingresado
        
        String cor=btn_act_correo.getText();
        String id=btnbuscarporid.getText();
        
        //2. Se valida que no existan vacíos
        
        if(cor.isEmpty()){
            
            JOptionPane.showMessageDialog(this, "El campo es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //3. El usuario ingresa dato para actualizar el campo de correo
        
        UserCRUD crud = new UserCRUD();
     
        //4. Se pregunta al usuario si desea actualizar el campo
        
        int respuesta = JOptionPane.showConfirmDialog(
            null, 
            "¿Estás seguro de que quieres actualizar el correo?", 
            "Confirmar actualización", 
            JOptionPane.YES_NO_OPTION
        );
        
        if (respuesta == JOptionPane.YES_OPTION){
            
                //5. Se muestra el status de la actualización/UPDATE
                
            //Si selecciona la opción "YES/SI" se hace la actualización 
            
            boolean status=crud.actualizar_correo_usuario(cor, id);
       
            
            if(status){
       JOptionPane.showMessageDialog(this,"Correo del usuario actualizado", "Éxito",JOptionPane.INFORMATION_MESSAGE);
            
        }
            
        }
            
        else
        {       
            //En caso contrario muestra el siguiente mensaje:
            JOptionPane.showMessageDialog(this,"Correo del usuario no actualizado",  "No actualizado",JOptionPane.INFORMATION_MESSAGE);  
        }
       limpiarcampos();
    }//GEN-LAST:event_btn_act_correoActionPerformed

    private void btn_act_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_act_contrasenaActionPerformed
       // TODO add your handling code here:
        //1. Se guarda en la variable lo que el usuario a ingresado
        
        String con=btn_act_contrasena.getText();
        String id=btnbuscarporid.getText();
        
        //2. Se valida que no existan vacíos
        
        if(con.isEmpty()){
            
            JOptionPane.showMessageDialog(this, "El campo es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        //3. El usuario ingresa dato para actualizar el campo de contrasena
        
        UserCRUD crud = new UserCRUD();
     
        //4. Se pregunta al usuario si desea actualizar el campo
        
        int respuesta = JOptionPane.showConfirmDialog(
            null, 
            "¿Estás seguro de que quieres actualizar la contraseña?", 
            "Confirmar actualización", 
            JOptionPane.YES_NO_OPTION
        );
        
        if (respuesta == JOptionPane.YES_OPTION){
            
                //5. Se muestra el status de la actualización/UPDATE
                
            //Si selecciona la opción "YES/SI" se hace la actualización, tomando en cuenta los parámetros de contraseña y id 
            
            boolean status=crud.actualizar_contrasena_usuario(con, id);
       
            
            if(status){
       JOptionPane.showMessageDialog(this,"Contraseña del usuario actualizada", "Éxito",JOptionPane.INFORMATION_MESSAGE);
            
        }
            
        }
            
        else
        {       
            //En caso contrario muestra el siguiente mensaje:
            JOptionPane.showMessageDialog(this,"Contraseña del usuario no actualizada",  "No actualizado",JOptionPane.INFORMATION_MESSAGE);  
        }
       limpiarcampos();
    }//GEN-LAST:event_btn_act_contrasenaActionPerformed

    private void limpiarcampos(){
        
        btn_act_nombre.setText("");
        btn_act_correo.setText("");
        btn_act_contrasena.setText("");
           
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_act_contrasena;
    private javax.swing.JButton btn_act_correo;
    private javax.swing.JButton btn_act_nombre;
    private javax.swing.JButton btnbuscarporid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane txtcontrasena;
    private javax.swing.JTextPane txtcorreo;
    private javax.swing.JTextPane txtid;
    private javax.swing.JTextPane txtnombre;
    // End of variables declaration//GEN-END:variables
}
